--- #YAML:1.0
name:                Business-ISMN
version:             1.11
abstract:            Work with International Standard Music Numbers
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    List::Util:                    0
    Test::More:                    0
    Tie::Cycle:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
