---
abstract: 'work with International Standard Music Numbers'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  Test::More: '0.95'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
  File::Spec::Functions: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-ISMN
no_index:
  directory:
    - t
    - inc
requires:
  List::Util: '0'
  Tie::Cycle: '1.21'
  perl: '5.008'
resources:
  bugtracker: https://github.com/briandfoy/business-ismn/issues
  homepage: https://github.com/briandfoy/business-ismn
  repository: https://github.com/briandfoy/business-ismn.git
version: '1.131'
