---
abstract: 'Work with International Standard Music Numbers'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0.95
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-ISMN
no_index:
  directory:
    - t
    - inc
requires:
  List::Util: 0
  Tie::Cycle: 0
resources:
  repository: https://github.com/briandfoy/business--isbn.git
version: 1.12
